param(
    [string]$OutputPath,
    [string]$CommitHash = "",
    [string]$BuildDate = ""
)

$lines = @(
    '// <auto-generated />',
    'using System.Reflection;',
    "[assembly: System.Reflection.AssemblyMetadata(""CommitHash"", ""$CommitHash"")]",
    "[assembly: System.Reflection.AssemblyMetadata(""BuildDate"", ""$BuildDate"")]"
)

Set-Content -Path $OutputPath -Value $lines -Encoding UTF8
