[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=1
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=Do you want to install MyCrownJewelApp Pfpad?
DisplayLicense=
FinishMessage=MyCrownJewelApp Pfpad has been installed successfully.
TargetName=MyCrownJewelApp.Pfpad.Installer.exe
FriendlyName=MyCrownJewelApp Pfpad Installer
AppLaunched=install.bat
PostInstallCmd=
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="install.bat"
FILE1="install.ps1"
[SourceFiles]
SourceFiles0=installer\
[SourceFiles0]
%FILE0%=
%FILE1%=